const ROUTES = {
  main: '/',
  progress: (reservationId?: number) => `progress/${reservationId || ':reservartionId'}`,
  bid: 'bid',
  feed: 'feed',
  map: 'map',
  search: 'search',
  loginCallback: 'callback',
  profile: 'profile',
  profileEdit: 'edit',
  profileEditPet: 'pet/edit/:petId',
  profileAddPet: 'pet/add',
  reviewDetail: 'review/:reviewId',
  portfolioDetail: 'portfolio/:portfolioId',
  reservation: 'reservation',
  designerProfile: 'designer/:designerId',
  review: 'review',
  reviewEdit: 'review/edit',
  login: 'login',
  signup: 'signup',
  signupSuccess: 'success',
  bidDetail: 'detail',
  bidRequest: 'request',
  bidTest: 'test',
  bidDesigner: 'designer',
  bidSuggest: 'suggest',
  bidDetailDesigner: 'detailDesigner',
  notification: 'notification',
} as const;

export default ROUTES;
