const ROUTES = {
  // main: '',
  // progress: 'progress',
  // bid: 'bid',
  signup: 'signup',
  main: '/',
  progress: (reservationId?: number) => `progress/${reservationId || ':reservartionId'}`,
  bid: 'bid',
  feed: 'feed',
  profile: 'profile',
  profileEdit: 'edit',
  profileEditPortfolio: 'edit/portfolio',
  portfolioDetail: 'portfolio/:portfolioId',
  reviewDetail: 'review/:reviewId',
  reservation: 'reservation',
  signupSuccess: 'success',
  membership: 'membership',
  registerProfile: 'register/profile',
  portfolio: 'portfolio',
  portfolioAdd: 'add',
  bidDetail: 'detail',
  bidRequest: 'request',
  bidTest: 'test',
  bidDesigner: 'designer',
  bidSuggest: 'suggest',
  bidDetailDesigner: 'detailDesigner',
  bidPastDetail: 'pastDetail',
} as const;

export default ROUTES;
